const constants = {
	CHANGE_SELECTED_POINTS: "CHANGE_SELECTED_POINTS",
	CHANGE_MARK_DRAW_LOCATION: "CHANGE_MARK_DRAW_LOCATION",
	CHANGE_ACTIVITIES: "CHANGE_ACTIVITIES",
	CHANGE_ABANDONED: "CHANGE_ABANDONED",
	CHANGE_DRAW_LOCATION: "CHANGE_DRAW_LOCATION"
};

export default constants;
